title:  Legal Negotiations Course Materials
description: 
theme: just-the-docs

url: https://daniel-burgos.github.io/GHLAbbott

aux_links:
  Template Repository: https://github.com/daniel-burgos/GHLAbbott
